import base.com.controller.complain_controller
import base.com.controller.dataset_controller
import base.com.controller.dataset_controller
import base.com.controller.degree_controller
import base.com.controller.department_controller
import base.com.controller.feedback_controller
import base.com.controller.home_controller
import base.com.controller.login_controller
import base.com.controller.prediction_controller
import base.com.controller.universitydetails_controller
import base.com.controller.universityinfo_controller
import base.com.controller.user_controller
